### ISSUE TITLE
Allow booking from Coming soon page

### ISSUE THREAD

**Issue by thisisoke** [oke-studio/acegolf#37]

**Comment by thisisoke** [comment]
Booking Request link Wiki here https://help.sevenrooms.com/hc/en-us/articles/8718626669851-Access-Rule-Guest-Duration-Picker

**Comment by efeosah** [comment]
> Booking Request link Wiki here https://help.sevenrooms.com/hc/en-us/articles/8718626669851-Access-Rule-Guest-Duration-Picker

This is taking me to a login page
