### ISSUE TITLE
Landing page v2

### ISSUE THREAD

**Issue by efeosah** [oke-studio/acegolf#40]
See new landing page design [here](https://www.figma.com/file/czLuxFms4pPCkJQ0CT2eAf/ACE?type=design&node-id=2150%3A3525&mode=design&t=sZMT89QM17Nil2oa-1)

**Comment by thisisoke** [comment]
This issue was a big push to redesign and implement the design to the website ahead of October 16 preview. we can now close this issue because the push was done
